# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/dist'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    CleanTargetFolder: true

- task: AzureFileCopy@4
  inputs:
    SourcePath: '$(Build.SourcesDirectory)/dist'
    azureSubscription: 'Free Trial (36336351-367e-43b2-ac0d-f9c329c67cd8)'
    Destination: 'AzureBlob'
    storage: 'sahelloworld2'
    ContainerName: '$web'
